# Site settings
title: Randika Rathugamage
description: Collection of my personal favorites wildlife photos
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/randika
googleplus_url:
instagram_url: http://instagram.com/randika.wildlife.photography
linkedin_url: https://www.linkedin.com/in/randika
pinterest_url:
slack_url:
twitter_url: https://twitter.com/iamrandika

# Build settings
markdown: kramdown
