# Site settings
title: Colors of Wild
description: "Welcome to 'Colors of Wild,' a captivating photo journal showcasing the untamed beauty of wildlife. As a passionate enthusiast from the beautiful Sri Lanka, I document animals in their natural habitats, celebrating the vibrant biodiversity of our planet through every photograph."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Randika Rathugamage
images_base_url: https://s3-ap-southeast-1.amazonaws.com/cdn.photography.lk/users/randika

# Collection settings
collections:
  photos:

# Social settings
500px_url:
#facebook_url: https://facebook.com/randika
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com/colorsofwild
#linkedin_url: https://www.linkedin.com/in/randika
pinterest_url:
slack_url:
#twitter_url: https://twitter.com/iamrandika

# Build settings
markdown: kramdown
