# Site settings
title: Wildlife Photography by Randika Rathugamage
description: Wildlife enthusiasts from the beautiful Sri Lanka. All photos of animals are taken in their natural habitats and available for sale. Follow me at <a href="https://instagram.com/randika.wildlife.photography">Instagram</a> for more photos.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Randika Rathugamage
images_base_url: https://s3-ap-southeast-1.amazonaws.com/cdn.photography.lk/users/randika

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url: https://facebook.com/randika
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com/randika.rathugamage
linkedin_url: https://www.linkedin.com/in/randika
pinterest_url:
slack_url:
twitter_url: https://twitter.com/iamrandika

# Build settings
markdown: kramdown
